name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: ${{secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: ${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}

steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven
  - name: Build with Maven
    run: mvn -B package --file pom.xml

  - name: Add coverage to PR
    id: jacoco
    uses: madrapps/jacoco-report@v1.3
    with:
      paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
      token: ${{ secrets.REPOSITORY_COMMIT_TOKEN}}

  - name: Log coverage percentage
    run: |
      echo "coverage overall = ${{ steps.jacoco.outputs.coverage-overall }}"
      echo "coverage changed files = ${{ steps.jacoco.outputs.coverage-changed-files }}"
